### PR TITLE
Migrating examples from main repo

### PR DESCRIPTION
**Pull request by okanasik**

### CODE REVIEW

**Comment by okanasik** [comment]
Dear @pushkalkatara I have some issues while trying to run prius examples. Did you develop these launch and world files yourself? First of all, gazebo is not able to find the models, you should add gazebo enviroment path update to the readme. Another issue is that there are unnecessary packages that are being run. For example, joystick package. Also world has some errors, at some corner of the world there is another field that is floating in the air. Can you check and fix these errors. Best,

**Comment by pushkalkatara** [comment]
Sir @okanasik , I think I pushed the original package of ToyotaPrius with the prius_spawn behavior. 
I have updated the package with the correct world, launch files and readme.

**Comment by okanasik** [comment]
@pushkalkatara It seems you changed only the readme file. Can you also update the launch file? Think about a visualstates user who just wants to test the given examples. Therefore, they do not need to run everything that runs with the current launch file. For example, there is no need to run rviz. Please check the launch file keep only nodes that are enough to run the example.

**Comment by pushkalkatara** [comment]
I changed the launch file too. Please find it in the commit - https://github.com/JdeRobot/VisualStates-examples/pull/1/commits/dd559937dc0e8dcb9e1944116e5a1e25db1a40f8

**Comment by okanasik** [comment]
Dear @pushkalkatara,
Yes, you are right, I miss the previous commit. I will comment when I test the pull request again. Best,

**Comment by okanasik** [comment]
Dear @pushkalkatara, It seems there are duplicate prius packages in `priusObstacleAvoidance` and `priusSpawn` directories. It would be better to have directory that have all common prius packages. Also, I will add common kobuki packages in a directory.

**Pull request merged**
