### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Aman-py**
first two examples not given right path, so given them right path

### CODE REVIEW

**Comment by pushkalkatara** [comment]
Hi Aman. PR looks good to me. Merging.

**Comment by pushkalkatara** [comment]
The issue still presists, #12 need gif for examples.

**Comment by Aman-py** [comment]
./kobuki_bump_and_go.py kobuki_bump_and_go.yml --displaygui==true
runtime gui disabled
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/aman-py/Downloads/VisualStates-examples-master/kobuki_bump_and_go/codegen/python/state.py", line 93, in run
    if tran.checkCondition():
  File "./kobuki_bump_and_go.py", line 95, in checkCondition
    self.namespace.calculate_obstacle()
AttributeError: 'Tran1' object has no attribute 'namespace'

Having this error whenever i try to execute this command:

./kobuki_bump_and_go.py kobuki_bump_and_go.yml --displaygui==true

**Comment by pushkalkatara** [comment]
Thanks for pointing out @Aman-py . I have created an issue related to this https://github.com/JdeRobot/VisualStates-examples/issues/13

**Pull request merged**
