### PR TITLE
Letter/Word/Sentence draw behavior

### PR DESCRIPTION
**Pull request by pushkalkatara**
Solves issue #8

### CODE REVIEW

**Comment by okanasik** [comment]
Everything looks perfect, but can you change the color of the letters from yellow to black. It is hard to perceive the yellow color on white background. Best.

**Comment by pushkalkatara** [comment]
I made the changes in the recent commit :D

**Comment by okanasik** [comment]
@pushkalkatara, I do not see the commit. Did you push to the repo?

**Comment by pushkalkatara** [comment]
Oops, sorry for the late reply. I made the necessary commit. :D

**Comment by okanasik** [comment]
fixes #9

**Pull request merged**
